# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
