# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PFapp', '0006_prefs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefs',
            old_name='face',
            new_name='bgcolor',
        ),
    ]
